### ISSUE TITLE
Can this be used to showcase CQ?

### ISSUE THREAD

**Issue by adam-urbanczyk** [greyltc/mechanical#1]
Is this repo at least partially CQ based? Could we use it to advertise CQ somewhere? If so, do you have any recommendations?

**Comment by greyltc** [comment]
Hey, sure.
I don't imagine many people would find the stuff here super interesting. It's mostly specialized little widgets. I might use CQ to generate stl files to 3d print the widgets or step files to get them milled out of aluminum.

Unfortunately, much of the code here probably won't run properly if you just clone the repo and try to run the python scripts. Most of the projects load in step files of circuit boards which I design in KiCad (the source for those generally lives in this other repo: https://github.com/greyltc/electronics ) Those PCB step files can get really big so they're not actually checked into git. Most of the stuff here uses a little helper lib, https://github.com/greyltc/mechanical/tree/master/geometrics which gets symlinked into the project folders, I don't know how/if those symlinks work on non-linux platforms.

You can run https://github.com/greyltc/mechanical/blob/master/scratch_tool/build.py and get some simple geometry for a little tool that helps us with one step of our solar cell fabrication process, but maybe that's not the greatest showcase:
![image](https://user-images.githubusercontent.com/16778174/110767032-b672c680-824d-11eb-81d1-90daf9363e96.png) 
![image](https://user-images.githubusercontent.com/16778174/110767109-c9859680-824d-11eb-8304-6dc746f774f2.png)

Running https://github.com/greyltc/mechanical/blob/master/sandwich/build.py makes:
![image](https://user-images.githubusercontent.com/16778174/110772006-115aec80-8253-11eb-8ec4-583410f07bfe.png)
which is a four piece holder for helping us make electrical connections to our little research solar cells for characterization.

Running https://github.com/greyltc/mechanical/blob/master/endblock/build.py makes this thing:
![image](https://user-images.githubusercontent.com/16778174/110773901-246ebc00-8255-11eb-9ab0-23cbddc6f5e3.png)
which is for mounting/aligning some PCBs in a larger assembly.

Running https://github.com/greyltc/mechanical/blob/master/groovy/build.py makes a dovetail o-ring groove (these are good for preventing the o-ring from coming unseated during use):
![image](https://user-images.githubusercontent.com/16778174/110776355-e1faae80-8257-11eb-8810-2afa453afa08.png)

**Comment by greyltc** [comment]
okay if I close this?
